//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab03_TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        public int id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string author { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> datepublished { get; set; }
        public Nullable<int> idCategory { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
